
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gestion_stock?createDatabaseIfNoExist=true&userSSL=false&useUnicode=true
    username:
    password:
#
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

server:
  port: 8081
